#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: fabric
  description: Hyperledger Fabric is an enterprise-grade permissioned distributed
    ledger framework for developing solutions and applications. Its modular and
    versatile design satisfies a broad range of industry use cases. It offers
    a unique approach to consensus that enables performance at scale while preserving
    privacy.
  homepage: https://wiki.hyperledger.org/display/fabric
  default_branch: main
  has_downloads: true
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
