site_name: Hyperledger Fabric
site_url: http://hyperledger-fabric.readthedocs.io
theme: readthedocs
repo_url: https://github.com/hyperledger/fabric.git
site_description: 'Welcome to the Hyperledger fabric documentation'
strict: true
theme_dir: 'docs/custom_theme'


pages:
- Home: index.md
- Glossary: glossary.md
- Protocol Spec: protocol-spec.md
- Usecases: biz/usecases.md

- Release Notes:
  - Migration Considerations: v0.6_migration.md
  - Releases: releases.md

- Starter Kit:
  - Starter Kit: starter/fabric-starter-kit.md

- Installation and Setup:
  - Chaincode or Application Developer Setup: Setup/Chaincode-setup.md
  - Java Chaincode Setup: Setup/JAVAChaincode.md
  - Fabric Network Setup: Setup/Network-setup.md
  - NodeSDK Setup: Setup/NodeSDK-setup.md
  - CA Setup: Setup/ca-setup.md
  - TLS Setup: Setup/TLSSetup.md
  - Logging: Setup/logging-control.md

- API's:
  - Chaincode APIs: API/ChaincodeAPI.md
  - Core API: API/CoreAPI.md
  - CA API: API/MemberServicesAPI.md
  - AttributesUsage API: API/AttributesUsage.md
  - System Chaincode: SystemChaincode-noop.md

- Fabric Developer:
  - v1.0 Preview: abstract_v1.md
  - Contributing: CONTRIBUTING.md
  - Maintainers: MAINTAINERS.md
  - Fabric Developer Setup: dev-setup/devenv.md
  - Building Fabric: dev-setup/build.md
  - Getting an Account: Gerrit/lf-account.md
  - Gerrit: Gerrit/gerrit.md
  - Reviewing: Gerrit/reviewing.md
  - Changes: Gerrit/changes.md
  - Best Practices: Gerrit/best-practices.md
- Go Style Guides:
    - Golang: Style-guides/go-style.md

- FAQ's:
  - ChainCodeFAQ: FAQ/chaincode_FAQ.md
  - ConfidentialityFAQ: FAQ/confidentiality_FAQ.md
  - ConsensusFAQ: FAQ/consensus_FAQ.md
  - Identity ManagementFAQ: FAQ/identity_management_FAQ.md
  - UsageFAQ: FAQ/usage_FAQ.md

- Tech:
  - Application ACL: tech/application-ACL.md
  - Attributes: tech/attributes.md
  - Best Practices: tech/best-practices.md

- NodeSDK:
  - App-developer-env-setup: nodeSDK/app-developer-env-setup.md
  - App-Overview: nodeSDK/app-overview.md
  - Node-SDK-guide: nodeSDK/node-sdk-guide.md
  - Node-SDK-indepth: nodeSDK/node-sdk-indepth.md
  - Sample-Standalone-app: nodeSDK/sample-standalone-app.md
  - Sample-web-app: nodeSDK/sample-web-app.md

markdown_extensions:
  - toc:
     permalink: true
  - admonition
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
  - footnotes

copyright: Copyright &copy; 2016 IBM Corp. <br></br>Contributed to the Hyperledger Project under the <a href="https://github.com/hyperledger/fabric/blob/master/LICENSE" target="_blank">Apache Software License 2.0</a>
