version: '2'
services:
  zookeeper:
    image: hyperledger/fabric-zookeeper

  kafka:
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
