version: '2'
networks:
   bridge:

services:

  ccenv_latest:
    container_name: ccenv_latest
    build: ./ccenv
    image: hyperledger/fabric-ccenv:latest
    volumes:
        - ./ccenv:/opt/gopath/src/github.com/hyperledger/fabric/orderer/ccenv

  ccenv_snapshot:
    container_name: ccenv_snapshot
    build: ./ccenv
    image: hyperledger/fabric-ccenv:x86_64-0.7.0-snapshot-c7b3fe0
    volumes:
        - ./ccenv:/opt/gopath/src/github.com/hyperledger/fabric/orderer/ccenv

  ca:
    image: sfhackfest22017/fabric-ca:x86_64-0.7.0-snapshot-6294c57
    ports:
      - 8054:7054
    environment:
      - CA_CERTIFICATE=peerOrg0_cert.pem
      - CA_KEY_CERTIFICATE=peerOrg0_pk.pem
    volumes:
        - ./tmp/ca:/.fabric-ca
    command: sh -c 'sleep 10; fabric-ca server start -ca /.fabric-ca/$$CA_CERTIFICATE -ca-key /.fabric-ca/$$CA_KEY_CERTIFICATE -config /etc/hyperledger/fabric-ca/server-config.json -address "0.0.0.0"'
    container_name: ca


  orderer:
    container_name: orderer
    image: sfhackfest22017/fabric-orderer:x86_64-0.7.0-snapshot-c7b3fe0
    environment:
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_BATCHTIMEOUT=10s
      - ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT=10
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      - ORDERER_GENERAL_ORDERERTYPE=solo
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_RAMLEDGER_HISTORY_SIZE=100
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    volumes:
      - ./tmp/orderer:/etc/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 8050:7050
    networks:
      - bridge

  peer0:
    container_name: peer0
    image: sfhackfest22017/fabric-peer:x86_64-0.7.0-snapshot-c7b3fe0
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer0
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer0
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    ports:
      - 8051:7051
      - 8053:7053
    links:
      - orderer:orderer
    volumes:
        - /var/run/:/host/var/run/
        - ./tmp/peer0:/etc/hyperledger/fabric/msp/sampleconfig
    networks:
      - bridge

  peer1:
    container_name: peer1
    image: sfhackfest22017/fabric-peer:x86_64-0.7.0-snapshot-c7b3fe0
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer0
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer1
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    ports:
      - 8055:7051
    command: peer node start --peer-defaultchain=false
    links:
      - orderer:orderer
      - peer0:peer0
    volumes:
        - /var/run/:/host/var/run/
        - ./tmp/peer1:/etc/hyperledger/fabric/msp/sampleconfig
    networks:
      - bridge

  peer2:
    container_name: peer2
    image: sfhackfest22017/fabric-peer:x86_64-0.7.0-snapshot-c7b3fe0
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer0
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer2
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer

    ports:
      - 8056:7051
    command: peer node start --peer-defaultchain=false
    links:
      - orderer:orderer
      - peer0:peer0
      - peer1:peer1
    volumes:
        - /var/run/:/host/var/run/
        - ./tmp/peer2:/etc/hyperledger/fabric/msp/sampleconfig
    networks:
      - bridge

  cli:
    container_name: cli
    image: sfhackfest22017/fabric-peer:x86_64-0.7.0-snapshot-c7b3fe0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_ADDRESS=peer0:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c './channel_test.sh; sleep 10000'
#   command: /bin/sh
    links:
      - orderer:orderer
      - peer0:peer0
      - peer1:peer1
      - peer2:peer2
    volumes:
        - /var/run/:/host/var/run/
        #in the "- <HOST>:/opt/gopath/src/github.com/hyperledger/fabric/examples/" mapping below, the HOST part
        #should be modified to the path on the host. This will work as is in the Vagrant environment
        - ./src/github.com/example_cc/example_cc.go:/opt/gopath/src/github.com/hyperledger/fabric/examples/example_cc.go
        - ./tmp/peer3/:/etc/hyperledger/fabric/msp/sampleconfig
        - ./channel_test.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel_test.sh
    networks:
      - bridge
