version: '2'
services:
  zookeeper:
    image: hyperledger/fabric-zookeeper

  orderer0:
    image: hyperledger/fabric-testenv-orderer
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092]
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - '7050'
    depends_on:
      - kafka0

  kafka0:
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
