version: "2"

services:

    vpNext:
        extends:
            file: compose-defaults.yml
            service: vp
        environment:
          - CORE_NEXT=true
          - CORE_PEER_ENDORSER_ENABLED=true
          - CORE_PEER_GOSSIP_ORGLEADER=false
          - CORE_PEER_GOSSIP_USELEADERELECTION=true

