version: "2"

services:

    ordererBase:
        image: hyperledger/fabric-orderer
        environment:
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - ORDERER_GENERAL_BATCHTIMEOUT=10s
            - ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT=10
            - ORDERER_GENERAL_MAXWINDOWSIZE=1000
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISIFILE=${ORDERER_GENERAL_GENESISIFILE}
            - ORDERER_RAMLEDGER_HISTORY_SIZE=100
        volumes:
            - ./volumes/orderer:/var/hyperledger/bddtests/volumes/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer

volumes:

    orderer:
