version: "2"

services:

    ordererBase:
        image: hyperledger/fabric-orderer
        environment:
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LOGLEVEL=debug
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - ORDERER_GENERAL_GENESISMETHOD=${ORDERER_GENERAL_GENESISMETHOD}
            #- ORDERER_GENERAL_GENESISMETHOD=provisional
            - ORDERER_GENERAL_GENESISFILE=${ORDERER_GENERAL_GENESISFILE}
            - ORDERER_GENERAL_QUEUESIZE=1000
            - ORDERER_GENERAL_MAXWINDOWSIZE=1000
            - ORDERER_RAMLEDGER_HISTORY_SIZE=100
            - ORDERER_GENERAL_BATCHSIZE=10
            - ORDERER_GENERAL_BATCHTIMEOUT=10s
        volumes:
            - ./volumes/orderer:/var/hyperledger/bddtests/volumes/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        ports:
          - '7050'

volumes:
    orderer:
