# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Build
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  GOPATH: /opt/go
  PATH: /opt/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GO_VER: 1.20.3

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  basic-checks:
    name: Basic Checks
    runs-on: fabric-ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: ${{ env.GO_VER }}
      - uses: actions/checkout@v3
        name: Checkout Fabric Code
        with:
          fetch-depth: 0
      - run: make basic-checks
        name: Run Basic Checks
  unit-tests:
    name: Unit Tests
    needs: basic-checks
    runs-on: fabric-ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: ${{ env.GO_VER }}
      - uses: actions/checkout@v3
        name: Checkout Fabric Code
      - run: ci/scripts/setup_hsm.sh
        name: Install SoftHSM
      - run: make unit-test
        name: Run Unit Tests
  integration-tests:
    name: Integration Tests
    needs: basic-checks
    strategy:
      fail-fast: false
      matrix:
        INTEGRATION_TEST_SUITE: ["raft","pvtdata","pvtdatapurge","ledger","lifecycle","e2e smartbft","discovery gossip devmode pluggable","gateway idemix pkcs11 configtx configtxlator","sbe nwo msp"]
    runs-on: fabric-ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: ${{ env.GO_VER }}
      - uses: actions/checkout@v3
        name: Checkout Fabric Code
      - run: ci/scripts/setup_hsm.sh
        name: Install SoftHSM
      - run: make integration-test INTEGRATION_TEST_SUITE="${{matrix.INTEGRATION_TEST_SUITE}}"
        name: Run Integration Tests
